name: Angular Test
on: 
  commit:
    branches: develop
    paths: 
    - 'ui/**'

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci && npm run lint && npm run build && npm run test
