name: Nginx CD

on:
  push:
    branches: [develop]
#    paths:
#     - "server/**"

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: nginx/.
          file: nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/express:latest
          # secrets: |
          #   GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
